config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'static_pages/home'
  get 'static_pages/help'
  get '/about', to: 'static_pages#about' 
  root 'static_pages#home'
  get '/sign_up', to: 'users#new' 
  get '/login', to: "session#new"
  post '/login', to: "session#create"
  delete '/logout', to: 'session#destroy'
  resources :users
  resources :account_activations, only: :edit
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :remember_token
  validates :name, presence:true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX },uniqueness: true

  validates :password, presence: true,length: {minimum:6},allow_nil:true,
    confirmation:true

  def forget
    update_attribute :remember_digest, nil
  end
  
  def remember
    self.remember_token = SecureRandom.urlsafe_base64 
    update_attribute :remember_digest, User.digest(remember_token)
  end
  def authenticate? token
    BCrypt::Password.new(remember_digest).is_password?(token)
    
  end
  
  class<<self
      def digest token
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost 
        BCrypt::Password.create(token, cost: cost)
      
      end
      
  end  
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include StaticPagesHelper
    include ApplicationHelper
    
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new

  end
  def destroy
    forget(current_user)
    session.delete(:user_id)
    @current_user= nil
    flash[:success] = "log out"
    redirect_to login_path
  end

  
  def create
   @user = User.find_by email: params[:session][:email]
   if @user.present? && @user.authenticate(params[:session][:password])
    session[:user_id] = @user.id
    login_user @user
    if params[:session][:remember_me] == "1"
      remember @user
    else
     forget @user
    end

    flash[:success] = "login successful"
    redirect_to @user
   else
    flash.now[:danger] = "email or password incorrect!!"
    render :new
   end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :login?, only: %i(show edit update)
    before_action :load_user, only: %i(show edit update destroy)
    before_action :correct_user?, only: %i( edit update)
    before_action :valid_admin?, only: %i( destroy)
    def show       
    end


    def index
     @users = User.paginate(page: params[:page])  
    end
    def destroy
        if @user.destroy
            flash[:success] = "delete success"            
        else
            flash[:success] = "delete fail"            
        end
        redirect_to users_path
    end   
    
    def update
        if @user.update user_params
            flash[:success] = "update success"
            redirect_to @user
        else
            flash[:danger] = "update fail"
            render :edit
        end 
    end
    def  new
        @user= User.new
    end
    def  edit
     
     end
    def create
        @user = User.new user_params      
        if @user.save
            flash[:success] = "create account successful"
            redirect_to @user
        else
            flash.now[:danger] = "create account failse"
            render :new #symbol
        end
    end
    private
    def user_params
        params.require(:user).permit :name, :email, :password, :password_confirmation
    end
    def load_user
        @user= User.find_by id: params[:id]  
        unless @user
            flash[:danger] = " not found user id: #{params[:id]}"
            redirect_to root_path
            
    end
    def correct_user?
        if current_user != @user
            flash[:danger] = "Access denied"
            redirect_to root_path
        end
    end
    def valid_admin?
        unless current_user.is_admin
        flash[:danger] = "Access denied"
        redirect_to user_path
        
    end
    
end 
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def login_user user
        session[:user_id]=user.id
    end
    def current_user       
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id=cookies.signed[:user_id])
            user=User.find_by id:user_id
            if user&.authenticate?(cookies[:remember_token])
                @current_user = user
            end
            
        end       
    end
    def remember user
        user.remember
        cookies.permanent[:remember_token] = @user.remember_token
        cookies.permanent.signed[:user_id] = @user.id
    end
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
       
    def login?
        return if current_user
       
         redirect_to login_path
         flash[:danger] = "u need login"
      
     end
    
end

app/helpers/session_helper.rb
module SessionHelper
 
       
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    def full_title page_title ="" 
           base_title ="Ruby on Rails Tutorial Sample App"  
           page_title.empty? ? base_title : "#{page_title} | #{base_title}"
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for user
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")

    end
end

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
   <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "error") %>.
   </div>
    <ul>
       <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
    <% end %>
    </ul>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
    <ul>
    <li><%= link_to "About", 'about_url' %></li>
    <li><%= link_to "Contact", '#' %></li>
    <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
    </nav>
    </footer>

app/views/layouts/_form.html.erb
<%= form_for(@user) do |f| %>
 <%= render "shared/error_messages", object: @user %>
 <%= f.label :name %>
 <%= f.text_field :name, class: "form-control" %>
 <%= f.label :email %>
 <%= f.email_field :email, class: "form-control" %>
 <%= f.label :password %>
 <%= f.password_field :password, class: "form-control" %>
 <%= f.label :password_confirmation %>
 <%= f.password_field :password_confirmation, class: "form-control" %>
 <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "sample app","#", id:"logo" %>
      <nav> 
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home","#" %></li>
          <li><%= link_to "Help","#" %></li>
        <% if current_user %>
        <li><%=link_to "Users", users_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
               <li><%= link_to "Profile", current_user %></li>
               <li><%= link_to "Settings", edit_user_path(current_user) %></li>
               <li class="divider"></li>
               <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li> 
          </ul>
        </li>
         
        <%else %>
          <li><%= link_to "Log in", login_path %></li>
        <%end %>
        
        </ul>
      </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> </title>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>  
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |type_msg, message| %>
      <div  class="alert alert-<%= type_msg%>" role="alert"><%= message %></div>
      <%end%>
      <%=yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

  </body>
  </html>

app/views/session/new.html.erb
<% provide(:title, "login") %>
<h1>login</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for :session , url: login_path do |f|  %>


        <%=f.label :email %>
        <%=f.email_field :email %>

        <%=f.label :password %>
        <%=f.password_field :password %>
        <%= f.label :remember_me, class: "checkbox inline" do %>
           <%= f.check_box :remember_me %>
           <span>Remember me on this computer</span>
            <%end%>

        <%= f.submit "log in", class:"btn  btn-primary" %>
        <%end%>
    </div>
</div>

app/views/static_pages/about.html.erb
<% provide :title, "About" %>
<h1>about page</h1>

app/views/static_pages/help.html.erb
<% provide :title,  "Help"%>


<h1>Help</h1>
<p>Get help on the Ruby on RailsTutorial at the
    <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>
    .Toget help on this sample app, see the<a href="http://www.railstutorial.org/book">
        <em>Ruby on Rails Tutorial</em> 
         book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide :title,  "Home"%>
<h1>Sample App</h1>
<p>
    Thisis the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> 
     sample application.
</p>

app/views/users/_form.html.erb
<%= form_for (@user)  do |f|  %>
    <%= render "layouts/error_messages" %>
    <%=f.label :name %>
    <%=f.text_field :name %>
    
    <%=f.label :email %>
    <%=f.email_field :email %>
    
    <%=f.label :password %>
    <%=f.password_field :password %>
    
    <%=f.label :password_conformation %>
    <%=f.password_field :password_conformation %>
    
    <%= f.submit title_submit, class:"btn  btn-primary" %>
    <%end%>

app/views/users/edit.html.erb
<% provide(:title, "Update account") %>

<h1>Update your profile</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
    <%= render "form", title_submit:"Save Changes"%>
    <div class="gravatar_edit">
        <%= gravatar_for @user%>
         <a href="http://gravatar.com/emails" target="_blank">change</a>
       </div>
</div>

</div>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1>All Users</h1>


<ul class="users">
    <% @users.each do |user|%>
        <li>
            <%=gravatar_for user%>
            <%=user.name%> |
            <%=user.email%>
           <% if current_user %>
           <% if current_user.is_admin && current_user!=user %>
            <%=link_to "Delete", user_path(user),method: :delete,
            class: "btn btn-danger", data:{confirm: "delete #{user.name} ?"} %>
            <% end%>
           <% end %>
        </li>
    <%end%>
    <%= will_paginate @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, "sign up") %>

<h1>Sign Up</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
    <%= render "form", title_submit:"Create Account"%>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
<aside class="col-md-4">
<section class="user_info">
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>
</section>
</aside>
</div>